# 时钟信号 (100 MHz 系统时钟)
set_property -dict {PACKAGE_PIN P17 IOSTANDARD LVCMOS33} [get_ports clk]
# # Define the generated 25MHz clock
# create_generated_clock -name clk_25mhz_derived #                        -source [get_pins clk_div_25mhz/clk_in] #                        -divide_by 4 #                        [get_pins clk_div_25mhz/clk_out]


# 复位信号 (CPU_RESET 按钮)
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports reset]

# 调试信号
# set_property -dict {PACKAGE_PIN D4 IOSTANDARD LVCMOS33} [get_ports debugMode]  # 拨码开关 SW0
# set_property -dict {PACKAGE_PIN D3 IOSTANDARD LVCMOS33} [get_ports step]       # 拨码开关 SW1
set_property IOSTANDARD LVCMOS33 [get_ports {button[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {button[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {button[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {button[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {button[0]}]
# 拨码开关 (SW2-SW9)
set_property -dict {PACKAGE_PIN P5 IOSTANDARD LVCMOS33} [get_ports {switch_in[15]}]
set_property -dict {PACKAGE_PIN P4 IOSTANDARD LVCMOS33} [get_ports {switch_in[14]}]
set_property -dict {PACKAGE_PIN P3 IOSTANDARD LVCMOS33} [get_ports {switch_in[13]}]
set_property -dict {PACKAGE_PIN P2 IOSTANDARD LVCMOS33} [get_ports {switch_in[12]}]
set_property -dict {PACKAGE_PIN R2 IOSTANDARD LVCMOS33} [get_ports {switch_in[11]}]
set_property -dict {PACKAGE_PIN M4 IOSTANDARD LVCMOS33} [get_ports {switch_in[10]}]
set_property -dict {PACKAGE_PIN N4 IOSTANDARD LVCMOS33} [get_ports {switch_in[9]}]
set_property -dict {PACKAGE_PIN R1 IOSTANDARD LVCMOS33} [get_ports {switch_in[8]}]
set_property -dict {PACKAGE_PIN U3 IOSTANDARD LVCMOS33} [get_ports {switch_in[7]}]
set_property -dict {PACKAGE_PIN U2 IOSTANDARD LVCMOS33} [get_ports {switch_in[6]}]
set_property -dict {PACKAGE_PIN V2 IOSTANDARD LVCMOS33} [get_ports {switch_in[5]}]
set_property -dict {PACKAGE_PIN V5 IOSTANDARD LVCMOS33} [get_ports {switch_in[4]}]
set_property -dict {PACKAGE_PIN V4 IOSTANDARD LVCMOS33} [get_ports {switch_in[3]}]
set_property -dict {PACKAGE_PIN R3 IOSTANDARD LVCMOS33} [get_ports {switch_in[2]}]
set_property -dict {PACKAGE_PIN T3 IOSTANDARD LVCMOS33} [get_ports {switch_in[1]}]
set_property -dict {PACKAGE_PIN T5 IOSTANDARD LVCMOS33} [get_ports {switch_in[0]}]
# 按钮 (BTN0)
# set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports button]
set_property PACKAGE_PIN U4 [get_ports {button[4]}]
set_property PACKAGE_PIN R17 [get_ports {button[3]}]
set_property PACKAGE_PIN V1 [get_ports {button[2]}]
set_property PACKAGE_PIN R11 [get_ports {button[1]}]
set_property PACKAGE_PIN R15 [get_ports {button[0]}]

# UART 接收信号 (USB-UART RX)
# set_property -dict {PACKAGE_PIN C4 IOSTANDARD LVCMOS33} [get_ports uart_rx]

# 波特率选择 (SW10-SW11)
# set_property -dict {PACKAGE_PIN A3 IOSTANDARD LVCMOS33} [get_ports {baud_select[1]}]
# set_property -dict {PACKAGE_PIN A4 IOSTANDARD LVCMOS33} [get_ports {baud_select[0]}]

# LED 输出 (LED0-LED7)
set_property -dict {PACKAGE_PIN F6 IOSTANDARD LVCMOS33} [get_ports {led[15]}]
set_property -dict {PACKAGE_PIN G4 IOSTANDARD LVCMOS33} [get_ports {led[14]}]
set_property -dict {PACKAGE_PIN G3 IOSTANDARD LVCMOS33} [get_ports {led[13]}]
set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVCMOS33} [get_ports {led[12]}]
set_property -dict {PACKAGE_PIN H4 IOSTANDARD LVCMOS33} [get_ports {led[11]}]
set_property -dict {PACKAGE_PIN J3 IOSTANDARD LVCMOS33} [get_ports {led[10]}]
set_property -dict {PACKAGE_PIN J2 IOSTANDARD LVCMOS33} [get_ports {led[9]}]
set_property -dict {PACKAGE_PIN K2 IOSTANDARD LVCMOS33} [get_ports {led[8]}]
#K1 H6 H5 J5 K6 L1 M1 K3
set_property -dict {PACKAGE_PIN K1 IOSTANDARD LVCMOS33} [get_ports {led[7]}]
set_property -dict {PACKAGE_PIN H6 IOSTANDARD LVCMOS33} [get_ports {led[6]}]
set_property -dict {PACKAGE_PIN H5 IOSTANDARD LVCMOS33} [get_ports {led[5]}]
set_property -dict {PACKAGE_PIN J5 IOSTANDARD LVCMOS33} [get_ports {led[4]}]
set_property -dict {PACKAGE_PIN K6 IOSTANDARD LVCMOS33} [get_ports {led[3]}]
set_property -dict {PACKAGE_PIN L1 IOSTANDARD LVCMOS33} [get_ports {led[2]}]
set_property -dict {PACKAGE_PIN M1 IOSTANDARD LVCMOS33} [get_ports {led[1]}]
set_property -dict {PACKAGE_PIN K3 IOSTANDARD LVCMOS33} [get_ports {led[0]}]

# 七段数码管 (SEG0-SEG6)
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg2[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg2[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg2[0]}]
set_property PACKAGE_PIN D4 [get_ports {seg1[0]}]
set_property PACKAGE_PIN E3 [get_ports {seg1[1]}]
set_property PACKAGE_PIN D3 [get_ports {seg1[2]}]
set_property PACKAGE_PIN F4 [get_ports {seg1[3]}]
set_property PACKAGE_PIN F3 [get_ports {seg1[4]}]
set_property PACKAGE_PIN E2 [get_ports {seg1[5]}]
set_property PACKAGE_PIN D2 [get_ports {seg1[6]}]
set_property PACKAGE_PIN H2 [get_ports {seg1[7]}]
set_property PACKAGE_PIN B4 [get_ports {seg2[0]}]
set_property PACKAGE_PIN A4 [get_ports {seg2[1]}]
set_property PACKAGE_PIN A3 [get_ports {seg2[2]}]
set_property PACKAGE_PIN B1 [get_ports {seg2[3]}]
set_property PACKAGE_PIN A1 [get_ports {seg2[4]}]
set_property PACKAGE_PIN B3 [get_ports {seg2[5]}]
set_property PACKAGE_PIN B2 [get_ports {seg2[6]}]
set_property PACKAGE_PIN D5 [get_ports {seg2[7]}]
set_property PACKAGE_PIN G2 [get_ports {tub_control[7]}]
set_property PACKAGE_PIN C2 [get_ports {tub_control[6]}]
set_property PACKAGE_PIN C1 [get_ports {tub_control[5]}]
set_property PACKAGE_PIN H1 [get_ports {tub_control[4]}]
set_property PACKAGE_PIN G1 [get_ports {tub_control[3]}]
set_property PACKAGE_PIN F1 [get_ports {tub_control[2]}]
set_property PACKAGE_PIN E1 [get_ports {tub_control[1]}]
set_property PACKAGE_PIN G6 [get_ports {tub_control[0]}]

# 七段数码管位选 (AN0-AN3)
# set_property -dict {PACKAGE_PIN J17 IOSTANDARD LVCMOS33} [get_ports {an[0]}]
# set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS33} [get_ports {an[1]}]
# set_property -dict {PACKAGE_PIN T9  IOSTANDARD LVCMOS33} [get_ports {an[2]}]
# set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports {an[3]}]

# VGA 输出
# set_property -dict {PACKAGE_PIN A3  IOSTANDARD LVCMOS33} [get_ports {vga_r[0]}]
# set_property -dict {PACKAGE_PIN B4  IOSTANDARD LVCMOS33} [get_ports {vga_r[1]}]
# set_property -dict {PACKAGE_PIN C5  IOSTANDARD LVCMOS33} [get_ports {vga_r[2]}]
# set_property -dict {PACKAGE_PIN A4  IOSTANDARD LVCMOS33} [get_ports {vga_r[3]}]
# set_property -dict {PACKAGE_PIN C6  IOSTANDARD LVCMOS33} [get_ports {vga_g[0]}]
# set_property -dict {PACKAGE_PIN A5  IOSTANDARD LVCMOS33} [get_ports {vga_g[1]}]
# set_property -dict {PACKAGE_PIN B6  IOSTANDARD LVCMOS33} [get_ports {vga_g[2]}]
# set_property -dict {PACKAGE_PIN A6  IOSTANDARD LVCMOS33} [get_ports {vga_g[3]}]
# set_property -dict {PACKAGE_PIN B7  IOSTANDARD LVCMOS33} [get_ports {vga_b[0]}]
# set_property -dict {PACKAGE_PIN C7  IOSTANDARD LVCMOS33} [get_ports {vga_b[1]}]
# set_property -dict {PACKAGE_PIN D7  IOSTANDARD LVCMOS33} [get_ports {vga_b[2]}]
# set_property -dict {PACKAGE_PIN D8  IOSTANDARD LVCMOS33} [get_ports {vga_b[3]}]
# set_property -dict {PACKAGE_PIN B11 IOSTANDARD LVCMOS33} [get_ports vga_hs]
# set_property -dict {PACKAGE_PIN B12 IOSTANDARD LVCMOS33} [get_ports vga_vs]

# 设置时序优化
# set_property CFGBVS VCCO [current_design]
# set_property CONFIG_VOLTAGE 3.3 [current_design]


